### ISSUE TITLE
Can not add Effects on skill and item, while it is inside a character sheet

### ISSUE THREAD

**Issue by wonkh11** [Tenyryas/lhtrpg#25]
It works fine when it is on the list.
but while accessing skills and items inside a chracter sheets, "Effects" can not be added or deleted or modified.
also, i don't know its bug or not but Effects inside Actors can be dragged an movable, but effects inside item/skill
can't be dragged

**Comment by Tenyryas** [comment]
This is sadly a core behaviour and current limitation of FoundryVTT, so it's not really something I'll be capable to fix for now. Sorry about that.

**Comment by Tenyryas** [comment]
You're in luck, the future V11 of FoundryVTT is tackling this exact issue. I'll try to see what I can do once V11 is a bit more advanced.

**Comment by wonkh11** [comment]
Awesome!!!

**Comment by Tenyryas** [comment]
Sorry for the delay, but at last the system has been ported to V11, which comes with the possibility to add effects on items and skills that are inside a character sheet.
